config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root to: "home#index"

  authenticate :user, lambda { |u| Rails.env.development? || u.superadmin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { sessions: "sessions" }

  devise_scope :user do
    get "login", to: "devise/sessions#new"
  end

  ActiveAdmin.routes(self)

  get :switch_lang, to: 'application#switch_lang'

  get "/pages/:page" => "pages#show", as: :page

  concern :contactable do
    post :contact, on: :member
  end

  resources :offers, concerns: :contactable
  resources :inquiries, concerns: :contactable
  resources :posts, concerns: :contactable
  resources :device_tokens, only: :create

  concern :accountable do
    get :give_time, on: :member
  end

  resources :organizations, except: [:new, :create, :destroy], concerns: :accountable do
    member do
      post :set_current
    end
  end
  get :select_organization, to: 'organizations#select_organization'

  get 'organization_transfers/new', to: 'organization_transfers#new', as: :new_organization_to_organization_transfer
  post 'organization_transfers', to: 'organization_transfers#create', as: :organization_to_organization_transfers
  resources :organization_alliances, only: [:index, :create, :update, :destroy] 
    
  resources :users, concerns: :accountable, except: :destroy, :path => "members" do
    collection do
      get 'signup'
      get 'manage'
      get 'please_confirm'
    end
  end
  put :update_avatar, to: 'users#update_avatar'

  resources :petitions, only: [:create, :update] do
    collection do
      get 'manage'
    end
  end

  resources :transfers, only: [:new, :create] do
    member do
      put :delete_reason
    end
  end
  match "multi/step/:step", to: "multi_transfers#step", via: [:get, :post], as: :multi_transfers_step
  post "multi/create", to: "multi_transfers#create", as: :multi_transfers_create

  resources :documents

  resources :members, only: [:destroy] do
    member do
      put :toggle_manager
      put :toggle_active
    end
  end

  resource "report" do
    collection do
      get "user_list"
      get "offer_list" => :post_list, type: "offer"
      get "inquiry_list" => :post_list, type: "inquiry"
      get "transfer_list"
      get "download_all"
    end
  end

  resource "statistics" do
    collection do
      get :global_activity
      get :inactive_users
      get :demographics
      get :last_login
      get :without_offers
      get :type_swaps
      get :all_transfers
    end
  end

  resource :terms, only: [:show] do
    post :accept
  end

  resources :tags, only: [:index] do
    collection do
      get :alpha_grouped_index
    end
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, :member_should_exist_and_be_active

  def index
    model = params[:model].classify.constantize
    posts = model.by_organization(current_organization)
    @tags = posts.find_like_tag(params[:term])

    render json: @tags
  end

  def alpha_grouped_index
    redirect_to users_path && return unless current_organization

    post_type = params[:post_type] || "user"
    @tags = case post_type
            when "offer"
              Offer.by_organization(current_organization).active.of_active_members
            when "inquiry"
              Inquiry.by_organization(current_organization).active.of_active_members
            when "user"
              Member.by_organization(current_organization).active
            end.alphabetical_grouped_tags

    respond_to do |format|
      format.html
      format.js do
        render partial: "grouped_index", locals: { alpha_tags: @tags, post_type: post_type }
      end
    end
  end
end

app/views/tags/_grouped_admin_checkboxes.html.haml
.row
  - i = 0
  - alpha_tags.each do |kg, vl|
    .col-xs-4.col-md-2
      %h2.bg-info.text-center
        = kg
      - vl.each do |tag, count|
        %p
          .badge
            = count
          - path = get_index_path(@current_post_type.pluralize, tag: tag)
          = link_to path do
            - gtag = (count == 1) ? "tag" : "tags"
            = glyph(gtag)
            = tag
          %label
            = check_box_tag "tags[]", tag, false, "ng-model" => "adminCheckModels[#{i}]"
        - i += 1

app/views/tags/_grouped_admin_index.html.haml
.tag_list.container_fluid
  .form-inline
    = form_tag action, "ng-controller" => "AdminCheckBoxesCtrl" do
      = render partial: "grouped_admin_checkboxes", locals: { alpha_tags: alpha_tags }
      .admin_tag_actions
        .row.reorganize_tags
          = hidden_field_tag :current_post_type, @current_post_type
          .col-xs-12.col-md-6.input-group
            - if action.eql?("/tags/destroy")
              = button_tag t("tags.alpha_grouped_destroy.delete"), id:"delete_button", name: "delete_button", value: "delete", method: "delete", data: { confirm: t("tags.alpha_grouped_rename.suremsg") }, class: "btn btn-danger reorganize_buttons", "ng-disabled" => "!isButtonEnabled()"
            - else
              = text_field_tag "new_name", nil, placeholder: t("tags.alpha_grouped_rename.rename_tag"), class: "form-control", "ng-disabled" => "!isButtonEnabled()", "ng-model" => "new_name"
              = button_tag t("tags.alpha_grouped_rename.merge"), id:"merge_button", name: "merge_button", value: "merge", method: "post", data: { confirm: t("tags.alpha_grouped_rename.suremsg") }, class: "btn btn-warning reorganize_buttons", "ng-disabled" => "!isMergeButtonEnabled()"

app/views/tags/_grouped_index.html.erb
<div class="tag_list container_fluid">
  <% alpha_tags.each_slice(6) do |gr| %>
    <div class="row">
      <% gr.each do |kg, vg| %>
        <div class="col-xs-12 col-sm-2">
          <h2 class="bg-info text-center">
            <%= kg %>
          </h2>
          <% vg.each do |tag, count| %>
            <p>
              <div class="badge rounded-pill bg-secondary">
                <%= count %>
              </div>
              <%= link_to [post_type.pluralize.to_sym, tag: tag] do %>
                <%= glyph count == 1 ? :tag : :tags %>
                <%= tag %>
              <% end %>
            </p>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/tags/_tag_type_selector.html.haml
%h1
  = maintitle
  - offer_checked = @current_post_type.eql?("offer")
  - inquiry_checked = !offer_checked
  - offer_checked_class = (offer_checked) ? "active" : ""
  - inquiry_checked_class = (inquiry_checked) ? "active" : ""
  - if defined? linkto
    .row
      = link_to Offer.model_name.human(count: :many), "#{linkto}?post_type=offer", class: "btn btn-primary #{switch_offer}_link #{offer_checked_class}"
      = link_to Inquiry.model_name.human(count: :many), "#{linkto}?post_type=inquiry", class: "btn btn-primary #{switch_inquiry}_link #{inquiry_checked_class}"
  - else
    = form_tag "/tags/alpha_grouped_index", method: :get do
      .btn-group{"data-toggle" => "buttons"}
        %label.btn.btn-primary{ class: "#{switch_offer} #{offer_checked_class}" }
          = radio_button_tag switch_offer, value: "offer", checked: offer_checked
          = Offer.model_name.human(count: :many)
        %label.btn.btn-primary{ class: "#{switch_inquiry} #{inquiry_checked_class}" }
          = radio_button_tag switch_inquiry, value: "inquiry", checked: inquiry_checked
          = Inquiry.model_name.human(count: :many)

app/views/tags/alpha_grouped_destroy.html.haml
= render partial: "tag_type_selector", locals: { maintitle: t(".maintitle"), switch_offer: "switch_offer_destroy", switch_inquiry: "switch_inquiry_destroy", linkto: "/tags/alpha_grouped_destroy" }

.tag_management
  .alpha_tag_list.col-xs-12
    = render partial: "grouped_admin_index", locals: { alpha_tags: @alpha_tags, action: "/tags/destroy" }

app/views/tags/alpha_grouped_index.html.erb
<h1><%= t '.maintitle' %></h1>

<%= form_tag alpha_grouped_index_tags_path, method: :get do %>
  <div class="btn-group switch-tags-js" data-toggle="buttons">
    <label class="btn btn-primary active switch_member-js">
      <%= radio_button_tag 'switch_member', 'user', true, class: "d-none" %>
      <%= t "users.index.members" %>
    </label>
    <label class="btn btn-primary switch_offer-js">
      <%= radio_button_tag 'switch_offer', 'offer', false, class: "d-none" %>
      <%= Offer.model_name.human count: :many %>
    </label>
    <label class="btn btn-primary switch_inquiry-js">
      <%= radio_button_tag 'switch_inquiry', 'inquiry', false, class: "d-none" %>
      <%= Inquiry.model_name.human count: :many %>
    </label>
  </div>
<% end %>

<div class="alpha_tag_list col-xs-12 col-md-12">
  <%= render 'grouped_index', alpha_tags: @tags, post_type: params[:post_type] || 'user' %>
</div>

app/views/tags/alpha_grouped_rename.html.haml
= render partial: "tag_type_selector", locals: { maintitle: t(".maintitle"), switch_offer: "switch_offer_rename", switch_inquiry: "switch_inquiry_rename", linkto: "/tags/alpha_grouped_rename" }

.tag_management
  .alpha_tag_list.col-xs-12
    = render partial: "grouped_admin_index", locals: { alpha_tags: @alpha_tags, action: "/tags/rename" }