config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root to: "home#index"

  authenticate :user, lambda { |u| Rails.env.development? || u.superadmin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { sessions: "sessions" }

  devise_scope :user do
    get "login", to: "devise/sessions#new"
  end

  ActiveAdmin.routes(self)

  get :switch_lang, to: 'application#switch_lang'

  get "/pages/:page" => "pages#show", as: :page

  concern :contactable do
    post :contact, on: :member
  end

  resources :offers, concerns: :contactable
  resources :inquiries, concerns: :contactable
  resources :posts, concerns: :contactable
  resources :device_tokens, only: :create

  concern :accountable do
    get :give_time, on: :member
  end

  resources :organizations, except: [:new, :create, :destroy], concerns: :accountable do
    member do
      post :set_current
    end
  end
  get :select_organization, to: 'organizations#select_organization'

  get 'organization_transfers/new', to: 'organization_transfers#new', as: :new_organization_to_organization_transfer
  post 'organization_transfers', to: 'organization_transfers#create', as: :organization_to_organization_transfers
  resources :organization_alliances, only: [:index, :create, :update, :destroy] 
    
  resources :users, concerns: :accountable, except: :destroy, :path => "members" do
    collection do
      get 'signup'
      get 'manage'
      get 'please_confirm'
    end
  end
  put :update_avatar, to: 'users#update_avatar'

  resources :petitions, only: [:create, :update] do
    collection do
      get 'manage'
    end
  end

  resources :transfers, only: [:new, :create] do
    member do
      put :delete_reason
    end
  end
  match "multi/step/:step", to: "multi_transfers#step", via: [:get, :post], as: :multi_transfers_step
  post "multi/create", to: "multi_transfers#create", as: :multi_transfers_create

  resources :documents

  resources :members, only: [:destroy] do
    member do
      put :toggle_manager
      put :toggle_active
    end
  end

  resource "report" do
    collection do
      get "user_list"
      get "offer_list" => :post_list, type: "offer"
      get "inquiry_list" => :post_list, type: "inquiry"
      get "transfer_list"
      get "download_all"
    end
  end

  resource "statistics" do
    collection do
      get :global_activity
      get :inactive_users
      get :demographics
      get :last_login
      get :without_offers
      get :type_swaps
      get :all_transfers
    end
  end

  resource :terms, only: [:show] do
    post :accept
  end

  resources :tags, only: [:index] do
    collection do
      get :alpha_grouped_index
    end
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/offer.rb
class Offer < Post
end

app/controllers/offers_controller.rb
class OffersController < PostsController
  def model
    Offer
  end

  def show
    super

    member = @offer.user.members.find_by(organization: @offer.organization)
    @destination_account = member.account if member
  end
end

app/views/offers/edit.html.erb
<h1>
  <%= @offer.title %>
  <small><%= t ".edit" %></small>
</h1>
<%= render 'shared/post_form', post: @offer, label_button: t(".submit") %>

app/views/offers/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>
      <%= Offer.model_name.human(count: :many) %>
      <%= render "shared/show_filter_hint" %>
    </h1>
  </div>
</div>

<div class="row">
  <%= render "shared/post_filters", base_path: offers_path %>

  <div class="col-md-4">
    <% if current_user && current_organization %>
      <ul class="nav navbar-nav text-end">
        <li class="nav-item">
          <%= link_to new_offer_path, class: 'nav-link text-primary' do %>
            <%= glyph :plus %>
            <%= t "helpers.submit.create", model: Offer.model_name.human %>
          <% end %>
        </li>
      </ul>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render "shared/posts", posts: @offers %>
  </div>
</div>

<%= paginate @offers %>

app/views/offers/new.html.erb
<h1>
  <%= t "helpers.submit.create", model: @offer.class.model_name.human %>
</h1>
<%= render 'shared/post_form', post: @offer, label_button: t(".submit") %>

app/views/offers/show.html.erb
<% if @offer.organization == current_organization %>
  <div class="actions text-end">
    <% if admin? or @offer.user == current_user %>
      <%= render 'shared/post_actions', post: @offer %>
    <% end %>
    <% if current_user and @offer.user != current_user %>
      <%= link_to new_transfer_path(id: @offer.user.id, offer: @offer.id, destination_account_id: @destination_account.id),
                  class: "btn btn-success" do %>
        <%= glyph :time %>
        <%= t ".give_time_for" %>
      <% end %>
    <% end %>
<% else %>
  <div class="actions text-end">
    <% if current_user and @offer.user != current_user %>
      <%= link_to new_transfer_path(id: @offer.user.id, offer: @offer.id, destination_account_id: @destination_account.id,
                                    organization_id: @offer.organization.id),
                  class: "btn btn-success" do %>
        <%= glyph :time %>
        <%= t ".give_time_for" %>
      <% end %>
    <% end %>
  </div>
<% end %>
<%= render "shared/post", post: @offer %>