config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root to: "home#index"

  authenticate :user, lambda { |u| Rails.env.development? || u.superadmin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { sessions: "sessions" }

  devise_scope :user do
    get "login", to: "devise/sessions#new"
  end

  ActiveAdmin.routes(self)

  get :switch_lang, to: 'application#switch_lang'

  get "/pages/:page" => "pages#show", as: :page

  concern :contactable do
    post :contact, on: :member
  end

  resources :offers, concerns: :contactable
  resources :inquiries, concerns: :contactable
  resources :posts, concerns: :contactable
  resources :device_tokens, only: :create

  concern :accountable do
    get :give_time, on: :member
  end

  resources :organizations, except: [:new, :create, :destroy], concerns: :accountable do
    member do
      post :set_current
    end
  end
  get :select_organization, to: 'organizations#select_organization'

  get 'organization_transfers/new', to: 'organization_transfers#new', as: :new_organization_to_organization_transfer
  post 'organization_transfers', to: 'organization_transfers#create', as: :organization_to_organization_transfers
  resources :organization_alliances, only: [:index, :create, :update, :destroy] 
    
  resources :users, concerns: :accountable, except: :destroy, :path => "members" do
    collection do
      get 'signup'
      get 'manage'
      get 'please_confirm'
    end
  end
  put :update_avatar, to: 'users#update_avatar'

  resources :petitions, only: [:create, :update] do
    collection do
      get 'manage'
    end
  end

  resources :transfers, only: [:new, :create] do
    member do
      put :delete_reason
    end
  end
  match "multi/step/:step", to: "multi_transfers#step", via: [:get, :post], as: :multi_transfers_step
  post "multi/create", to: "multi_transfers#create", as: :multi_transfers_create

  resources :documents

  resources :members, only: [:destroy] do
    member do
      put :toggle_manager
      put :toggle_active
    end
  end

  resource "report" do
    collection do
      get "user_list"
      get "offer_list" => :post_list, type: "offer"
      get "inquiry_list" => :post_list, type: "inquiry"
      get "transfer_list"
      get "download_all"
    end
  end

  resource "statistics" do
    collection do
      get :global_activity
      get :inactive_users
      get :demographics
      get :last_login
      get :without_offers
      get :type_swaps
      get :all_transfers
    end
  end

  resource :terms, only: [:show] do
    post :accept
  end

  resources :tags, only: [:index] do
    collection do
      get :alpha_grouped_index
    end
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/transfer.rb
# A time transfer between accounts.
#
# When an amount of time is to be transferred between two accounts, a
# Transfer object should be created with the following attributes:
#
# source: id or instance of the source account
# destination: id or instance of the destination account
# amount: integer amount of time to transfer
#
# Along with the transfer, two movements are created, one in each related
# account, so the total sum of the system is zero
#
class Transfer < ApplicationRecord
  attr_accessor :source, :destination, :amount, :hours, :minutes

  belongs_to :post, optional: true
  has_many :movements, dependent: :destroy
  has_many :events, dependent: :destroy

  validates :amount, numericality: { greater_than: 0 }
  validate :different_source_and_destination

  after_create :make_movements

  def make_movements
    movements.create(account: Account.find(source_id), amount: -amount.to_i, created_at: created_at)
    movements.create(account: Account.find(destination_id), amount: amount.to_i, created_at: created_at)
  end

  def source_id
    source.respond_to?(:id) ? source.id : source
  end

  def destination_id
    destination.respond_to?(:id) ? destination.id : destination
  end

  private

  def different_source_and_destination
    return unless source == destination
    errors.add(:base, :same_account)
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  include WithTransferParams

  def create
    @source = find_source
    @account = Account.find(transfer_params[:destination])

    create_persisters

    if persisters_saved?
      redirect_to redirect_target
    else
      redirect_back fallback_location: redirect_target, alert: @transfer.errors.full_messages.to_sentence
    end
  end

  def new
    transfer_factory = TransferFactory.new(
      current_organization,
      current_user,
      params[:offer],
      params[:destination_account_id],
      params[:organization_id] || current_organization.id
    )

    render(
      :new,
      locals: {
        accountable: transfer_factory.accountable,
        transfer: transfer_factory.build_transfer,
        offer: transfer_factory.offer,
        sources: transfer_factory.transfer_sources
      }
    )
  end

  def delete_reason
    @transfer = Transfer.find(params[:id])
    @transfer.update_columns(reason: nil)

    respond_to do |format|
      format.json { head :ok }
      format.html { redirect_back(fallback_location: request.referer) }
    end
  end

  private

  def find_source
    if admin?
      Account.find(transfer_params[:source])
    else
      current_user.members.find_by(organization: current_organization).account
    end
  end

  def create_persisters
    source_organization = @source.organization.account
    source_type = @source.accountable_type
    destination_organization = @account.organization.account
    @persisters = Array.new
    if source_organization == destination_organization
      transfer_persister_between(@source, @account)
    else
      transfer_persister_between(@source, source_organization) if source_type == "Member"
      transfer_persister_between(source_organization, destination_organization)
      transfer_persister_between(destination_organization, @account)
    end
  end

  def transfer_persister_between(source, destination)
    @transfer = Transfer.new(
      transfer_params.merge(source: source, destination: destination)
    )

    @persisters << ::Persister::TransferPersister.new(@transfer)
  end

  def persisters_saved?
    @persisters.each { |persister| return false if !persister.save }
  end

  def redirect_target
    case accountable = @account.accountable
    when Organization
      accountable
    when Member
      accountable.organization == current_organization ? accountable.user : accountable.organization
    else
      raise ArgumentError
    end
  end
end

app/helpers/transfers_helper.rb
module TransfersHelper
  def accountable_path(accountable)
    if accountable.is_a?(Organization)
      organization_path(accountable)
    else
      user_path(accountable.user)
    end
  end

  def accounts_from_movements(transfer, with_links: false)
    transfer.movements.sort_by(&:amount).map do |movement|
      account = movement.account

      if account.accountable.blank?
        I18n.t('users.show.deleted_user')
      elsif account.accountable_type == 'Organization'
        link_to_if(with_links, account, organization_path(account.accountable))
      elsif account.accountable.active
        link_to_if(with_links, account.accountable.display_name_with_uid, user_path(account.accountable.user))
      else
        I18n.t('users.show.inactive_user')
      end
    end
  end

  def is_bank_to_bank_transfer?(transfer)
    return false unless transfer

    source_account = transfer.movements.find_by('amount < 0')&.account
    destination_account = transfer.movements.find_by('amount > 0')&.account

    source_account&.accountable_type == 'Organization' &&
    destination_account&.accountable_type == 'Organization' &&
    transfer.post.nil?
  end
end

app/views/transfers/_form.html.haml
= simple_form_for(@transfer) do |f|
  = f.error_notification

  .form-inputs
    = f.fields_for :inbound_movement do |in_m|
      = in_m.association :user
    = f.fields_for :outbound_movement do |out_m|
      = in_m.association :user
    = f.input :amount
    = f.association :category
    = f.input :date

  .form-actions
    = f.button :submit

app/views/transfers/_member_offer.html.erb
<% if offer %>
  <%= form.input :post, readonly: true %>
  <%= form.input :post_id, as: :hidden %>
<% else %>
<%
input_options = { collection: accountable.offers.active }

if local_assigns[:value]
  input_options[:selected] = local_assigns[:value]
end
%>

<%= form.input :post_id, input_options %>
<% end %>

app/views/transfers/_organization_offer.html.erb
<% if offer %>
  <%= form.input :post, as: :hidden %>
<% end %>

app/views/transfers/edit.html.haml
%h1 Editing transfer

= render 'form'

= link_to 'Show', @transfer
\|
= link_to 'Back', transfers_path

app/views/transfers/index.html.haml
%h1 Listing transfers

%table
  %tr
    %th User
    %th Amount
    %th Category
    %th Date
    %th
    %th
    %th

  - @transfers.each do |transfer|
    %tr
      %td= transfer.user
      %td= transfer.amount
      %td= transfer.category
      %td= transfer.date
      %td= link_to 'Show', transfer
      %td= link_to 'Edit', edit_transfer_path(transfer)
      %td= link_to 'Destroy', transfer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Transfer', new_transfer_path

app/views/transfers/new.html.erb
<h1>
  <small><%= t ".give_time" %></small>
  <%= link_to accountable.try(:display_name_with_uid) || offer.user.username, accountable_path(accountable) || offer.user %>
</h1>

<% if offer %>
  <h3><%= offer %></h3>
  <% if cross_bank %>
    <div class="alert bg-info">
      <%= t 'transfers.cross_bank.info', organization: offer.organization.name %>
    </div>
  <% end %>
<% end %>

<%= simple_form_for transfer do |f| %>
  <div class="form-inputs">
    <%= f.input :hours,
                as: :integer,
                input_html: {
                  min: 0,
                  "data-rule-either-hours-minutes-informed" => "true"
                } %>
    <%= f.input :minutes,
                as: :integer,
                input_html: {
                  min: 0,
                  max: 59,
                  step: 15,
                  "data-rule-either-hours-minutes-informed" => "true",
                  "data-rule-range" => "[0,59]"
                } %>
    <%= f.input :amount, as: :hidden %>
    <%= f.input :reason %>
    
    <% if cross_bank %>
      <%= hidden_field_tag :cross_bank, "true" %>
      <%= hidden_field_tag :post_id, offer.id %>
    <% else %>
      <%= f.input :destination, as: :hidden %>
    <% end %>

    <% if sources.present? %>
      <div class="mb-3">
        <%= f.label :source, class: "form-label" %>
        <%= f.select :source,
          options_for_select(
            TransferSourcesOptions.new(sources).to_a,
            selected: current_user.member(current_organization).account.id
          ), {}, id: "select2", class: "form-control"
        %>
      </div>
    <% end %>

    <% unless cross_bank %>
      <%= render partial: "#{accountable.model_name.singular}_offer", locals: { form: f, offer: offer, accountable: accountable } %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-secondary", data: { disable_with: "..." } %>
    <label class="js-error-amount form-label error invisible"><%= t ".error_amount" %></label>
  </div>
<% end %>

app/views/transfers/new.html.haml
.page-header
  %h1
    %i.icon-time.icon-border
    New Transfer

= render 'form'

= link_to 'Back', transfers_path

app/views/transfers/organization.html.erb
<h1>
  <small><%= t '.give_time' %></small>
  <%= link_to @organization, organization_path(@organization) %>
</h1>
<% if @offer %>
  <h3>
    <%= @offer %>
  </h3>
<% end %>
<%= simple_form_for @transfer do |f| %>
  <div class="form-inputs">
    <%= f.input :hours,
                as: :integer,
                input_html: {
                  min: 0,
                  max: 20,
                  'data-rule-either-hours-minutes-informed' => 'true',
                  'data-rule-range' => '[0,20]'
                } %>
    <%= f.input :minutes,
                as: :integer,
                input_html: {
                  min: 0,
                  max: 59,
                  step: 15,
                  'data-rule-either-hours-minutes-informed' => 'true',
                  'data-rule-range' => '[0,59]'
                } %>
    <%= f.input :amount, as: :hidden %>
    <%= f.input :reason %>
    <%= f.input :destination, as: :hidden %>
    <% if admin? %>
      <div class="form-group">
        <%= f.label :source %>
        <%# TODO: refactor. it's very complex for a view. %>
        <%= f.select :source,
                     options_for_select(
                       @sources.sort_by { |source| [source.accountable_type, source.accountable_id] }
                               .map { |a| ["#{a.accountable_type == 'Member' ? a.accountable.member_uid : a.accountable_id} #{a.accountable_type} #{a.accountable.to_s}", a.id] },
                       selected: current_user.member(current_organization).account.id
                     ),
                     {},
                     id: 'select2-time',
                     class: 'form-control' %>
      </div>
    <% end %>
    <% if @offer %>
      <%= f.input :post, as: :hidden %>
    <% end %>
  </div>
  <div class="form-actions">
    <%= f.button :submit,
                 class: 'btn btn-default',
                 style: 'margin-bottom: 20px;' %>
  </div>
<% end %>
<script>
  $("#select2-time").select2({
    formatNoMatches: function () {
        return "<%= j t('application.tips.user_not_found') %>";
    }
  });
</script>

app/views/transfers/show.html.haml
%p#notice= notice

%p
  %b User:
  = @transfer.user
%p
  %b Amount:
  = @transfer.amount
%p
  %b Category:
  = @transfer.category
%p
  %b Date:
  = @transfer.date

= link_to 'Edit', edit_transfer_path(@transfer)
\|
= link_to 'Back', transfers_path