config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root to: "home#index"

  authenticate :user, lambda { |u| Rails.env.development? || u.superadmin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { sessions: "sessions" }

  devise_scope :user do
    get "login", to: "devise/sessions#new"
  end

  ActiveAdmin.routes(self)

  get :switch_lang, to: 'application#switch_lang'

  get "/pages/:page" => "pages#show", as: :page

  concern :contactable do
    post :contact, on: :member
  end

  resources :offers, concerns: :contactable
  resources :inquiries, concerns: :contactable
  resources :posts, concerns: :contactable
  resources :device_tokens, only: :create

  concern :accountable do
    get :give_time, on: :member
  end

  resources :organizations, except: [:new, :create, :destroy], concerns: :accountable do
    member do
      post :set_current
    end
  end
  get :select_organization, to: 'organizations#select_organization'

  get 'organization_transfers/new', to: 'organization_transfers#new', as: :new_organization_to_organization_transfer
  post 'organization_transfers', to: 'organization_transfers#create', as: :organization_to_organization_transfers
  resources :organization_alliances, only: [:index, :create, :update, :destroy] 
    
  resources :users, concerns: :accountable, except: :destroy, :path => "members" do
    collection do
      get 'signup'
      get 'manage'
      get 'please_confirm'
    end
  end
  put :update_avatar, to: 'users#update_avatar'

  resources :petitions, only: [:create, :update] do
    collection do
      get 'manage'
    end
  end

  resources :transfers, only: [:new, :create] do
    member do
      put :delete_reason
    end
  end
  match "multi/step/:step", to: "multi_transfers#step", via: [:get, :post], as: :multi_transfers_step
  post "multi/create", to: "multi_transfers#create", as: :multi_transfers_create

  resources :documents

  resources :members, only: [:destroy] do
    member do
      put :toggle_manager
      put :toggle_active
    end
  end

  resource "report" do
    collection do
      get "user_list"
      get "offer_list" => :post_list, type: "offer"
      get "inquiry_list" => :post_list, type: "inquiry"
      get "transfer_list"
      get "download_all"
    end
  end

  resource "statistics" do
    collection do
      get :global_activity
      get :inactive_users
      get :demographics
      get :last_login
      get :without_offers
      get :type_swaps
      get :all_transfers
    end
  end

  resource :terms, only: [:show] do
    post :accept
  end

  resources :tags, only: [:index] do
    collection do
      get :alpha_grouped_index
    end
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/organization.rb
class Organization < ApplicationRecord
  include PgSearch::Model

  pg_search_scope :search_by_query,
    against: %i[city neighborhood address name],
    ignoring: :accents,
    using: {
      tsearch: {
        prefix: true
      }
    }

  has_one_attached :logo

  has_many :members, dependent: :destroy
  has_many :users, -> { order "members.created_at DESC" }, through: :members
  has_many :all_accounts, class_name: "Account", inverse_of: :organization, dependent: :destroy
  has_many :all_movements, class_name: "Movement", through: :all_accounts, source: :movements
  has_many :all_transfers, class_name: "Transfer", through: :all_movements, source: :transfer
  has_one :account, as: :accountable, dependent: :destroy
  has_many :member_accounts, through: :members, source: :account
  has_many :posts, dependent: :destroy
  has_many :offers
  has_many :inquiries
  has_many :documents, as: :documentable, dependent: :destroy
  has_many :petitions, dependent: :delete_all

  validates :name, presence: true, uniqueness: true

  LOGO_CONTENT_TYPES = %w(image/jpeg image/png image/gif)
  validates :logo, content_type: LOGO_CONTENT_TYPES

  before_validation :ensure_url
  after_create :create_account

  def to_s
    "#{name}"
  end

  def all_transfers_with_accounts
    all_transfers.
      includes(movements: { account: :accountable }).
      order("transfers.created_at DESC").
      distinct
  end

  def all_managers
    users.where(members: { manager: true })
  end

  def display_name_with_uid
    self
  end

  # Returns the id to be displayed in the :new transfer page with the given
  # destination_accountable
  #
  # @params destination_accountable [Organization | Object] target of a transfer
  # @return [Integer | String]
  def display_id
    account.accountable_id
  end

  def ensure_reg_number_seq!
    update_column(:reg_number_seq, members.maximum(:member_uid))
  end

  def ensure_reg_number_seq
    ensure_reg_number_seq! unless reg_number_seq
  end

  def next_reg_number_seq
    ensure_reg_number_seq
    increment!(:reg_number_seq)
    reg_number_seq
  end

  def global_balance
    Account.where(organization_id: id).sum(:balance)
  end

  def ensure_url
    return if web.blank? || URI.parse(web).is_a?(URI::HTTP)
  rescue
    errors.add(:web, :url_format_invalid)
  else
    if URI.parse("http://#{web}").is_a?(URI::HTTP)
      self.web = "http://#{web}"
    else
      errors.add(:web, :url_format_invalid)
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :load_resource, only: [:show, :edit, :update, :set_current]
  before_action :user_should_be_confirmed

  def index
    if current_user
      user_organizations  = Organization.left_outer_joins(:petitions).where(petitions: { user_id: current_user.id })
      @user_organizations = user_organizations.or(Organization.where(id: current_user.organizations.pluck(:id))).distinct
    end

    organizations  = Organization.where.not(id: @user_organizations&.pluck(:id))
    organizations  = organizations.search_by_query(params[:q]) if params[:q].present?
    @organizations = organizations.order(highlighted: :desc).page(params[:page]).per(25)
  end

  def show
    @movements = @organization.
                 account.
                 movements.
                 order("created_at DESC").
                 page(params[:page]).
                 per(10)
  end

  def update
    if @organization.update(organization_params)
      redirect_to @organization
    else
      render action: :edit, status: :unprocessable_entity
    end
  end

  def set_current
    if current_user
      session[:current_organization_id] = @organization.id
    end
    redirect_to root_path
  end

  def select_organization
    @organizations = current_user.organizations
  end

  private

  def load_resource
    @organization = Organization.find(params[:id])

    authorize @organization
  end

  def organization_params
    params[:organization].permit(*%w[name theme email phone web
                                     public_opening_times description address
                                     neighborhood city domain logo])
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
  def filterable_organizations
    Organization.all.order(:name)
  end

  def allied_organizations
    return [] unless current_organization

    allied_org_ids = current_organization.accepted_alliances.map do |alliance|
      alliance.source_organization_id == current_organization.id ?
        alliance.target_organization_id : alliance.source_organization_id
    end

    organizations = Organization.where(id: allied_org_ids + [current_organization.id])
    organizations.order(:name)
  end
end

app/views/organizations/_alliance_button.html.erb
<% if current_user&.manages?(current_organization) && organization != current_organization %>
  <% alliance = current_organization.alliance_with(organization) %>
  <% if alliance.nil? %>
    <%= link_to t('organization_alliances.request_alliance'),
          organization_alliances_path(organization_alliance: { target_organization_id: organization.id }),
          method: :post,
          class: 'btn btn-secondary',
          aria: { label: t('organization_alliances.request_alliance_for', org: organization.name) } %>
  <% elsif alliance.pending? %>
    <span class="badge rounded-pill bg-secondary"><%= t('organization_alliances.pending') %></span>
  <% elsif alliance.accepted? %>
    <span class="badge rounded-pill bg-primary"><%= t('organization_alliances.active') %></span>
  <% elsif alliance.rejected? %>
    <span class="badge rounded-pill bg-danger"><%= t('organization_alliances.rejected') %></span>
  <% end %>
<% end %>

app/views/organizations/_form.html.erb
<%= show_error_messages!(@organization) %>
<%= simple_form_for @organization do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :phone %>
  <%= f.input :web %>
  <%= f.input :description %>
  <%= f.input :public_opening_times %>
  <%= f.input :address %>
  <%= f.input :neighborhood %>
  <%= f.input :city %>
  <%= f.input :logo, input_html: { accept: Organization::LOGO_CONTENT_TYPES.join(',') } %>
  <%= f.button :submit %>
<% end %>

app/views/organizations/_organizations_row.html.erb
<tr>
  <td><%= link_to(org.name, org) %></td>
  <td><%= org.city %></td>
  <td><%= org.neighborhood %></td>
  <td><%= link_to(org.web, org.web) if org.web.present? %></td>
  <td><%= org.members.count %></td>
  <td>
    <%= render "organizations/petition_button", organization: org %>
  </td>
  <% if current_user&.manages?(current_organization) %>
    <td>
      <%= render "organizations/alliance_button", organization: org %>
    </td>
  <% end %>
</tr>

app/views/organizations/_petition_button.html.erb
<% if current_user %>
  <% petition = current_user.petitions.where(organization_id: organization.id).last %>

  <% if member = Member.where(user: current_user, organization: organization).first %>
    <%= link_to t('users.user_rows.delete_membership'),
          member,
          method: :delete,
          data: { confirm: t('users.user_rows.sure_delete', organization_name: organization.name) },
          class: 'btn btn-danger' %>
  <% elsif petition && !current_user.was_member?(petition) %>
    <span class="badge rounded-pill bg-secondary"><%= petition.status %></span>
  <% else %>
    <%= link_to t('petitions.apply'),
          petitions_path(user_id: current_user.id, organization_id: organization.id),
          method: :post,
          class: 'btn btn-secondary' %>
  <% end %>
<% end %>

app/views/organizations/edit.html.erb
<h1>
  <%= link_to @organization, organization_path(@organization) %>
  <small><%= t 'global.edit' %></small>
</h1>
<%= render 'form' %>

app/views/organizations/index.html.erb
<h1>
  <%= Organization.model_name.human(count: :many) %>
</h1>

<div class="row">
  <div class="col-md-6">
    <form action="<%= organizations_path %>" class="form-inline mb-2 d-flex navbar-left" method="get">
        <input class="form-control d-inline w-auto"
               name="q"
               placeholder="<%= t "global.search_location" %>"
               type="text"
               value="<%= params[:q] %>">
      <button class="btn btn-secondary ms-1" type="submit"><%= t "global.search" %></button>
    </form>
  </div>
</div>

<div class="card">
  <div class="card-body table-responsive">
    <table class="table table-hover table-sm">
      <thead>
        <tr>
          <th></th>
          <th><%= t '.city' %></th>
          <th><%= t '.neighborhood' %></th>
          <th><%= t '.web' %></th>
          <th><%= t '.member_count' %></th>
          <th><%= t '.membership' %></th>
          <% if current_user&.manages?(current_organization) %>
            <th><%= t '.alliance' %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'organizations_row', collection: @user_organizations, as: :org if !params[:page] || params[:page] == '1' %>
        <%= render partial: 'organizations_row', collection: @organizations, as: :org %>
      </tbody>
    </table>
    <div class="paginate-align">
      <%= paginate @organizations %>
    </div>
  </div>
</div>

app/views/organizations/select_organization.html.erb
<div class="card">
  <div class="card-body table-responsive">
    <table class='table table-hover table-sm'>
      <thead>
        <tr>
          <th><%= t 'activerecord.attributes.organization.name' %></th>
          <th><%= t 'global.information' %></th>
          <th><%= t 'global.enter_to_timebank' %></th>
        </tr>
      </thead>
      <tbody>
        <% @organizations.each_with_index do |organization, index| %>
          <tr>
            <td><%= organization.name %></td>
            <td><a href='#' data-bs-toggle='modal' data-bs-target='#org_dialog<%= index %>'> <%= t 'global.show' %></a></td>
            <td>
              <% if current_user.active?(organization) %>
                <%= link_to set_current_organization_path(organization), method: :post do %>
                  <%= glyph 'arrow-right' %>
                  <%= t 'application.landing.button' %>
                <% end %>
              <% else %>
                <span class="badge bg-secondary"><%= t 'activerecord.attributes.user.deactivated' %></span>
              <% end %>
            </td>
          </tr>

          <div class='modal fade' id='org_dialog<%= index %>'>
            <div class='modal-dialog modal-dialog-centered'>
              <div class='modal-content'>
                <div class='modal-header'>
                  <h4 class='modal-title'><%= organization.name %></h4>
                  <button type='button' class='btn-close' data-bs-dismiss='modal'> </button>
                </div>
                <div class='modal-body'>
                  <strong><%= t 'activerecord.attributes.organization.address' %>:</strong>
                  <%= organization.address %> <%= organization.neighborhood %> <%= organization.city %>
                  <br>
                  <strong><%= t 'activerecord.attributes.organization.phone' %>:</strong>
                  <%= organization.phone %>
                  <br>
                  <strong><%= t 'activerecord.attributes.organization.email'%>:</strong>
                  <%= organization.email %>
                  <br>
                  <strong>Web:</strong>
                  <a href="<%= organization.web %>"><%= organization.web %></a>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class='alert alert-info'>
  * <%= t 'users.index.deactivated_warning' %>
</div>

app/views/organizations/show.html.erb
<h1>
  <%= link_to @organization, organization_path(@organization) %>
</h1>
<div class="row mb-4">
  <div class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">
          <%= t '.contact_information' %>
        </h3>
      </div>
      <div class="card-body">
        <p>
          <strong>
            <%= Organization.human_attribute_name 'email' %>
          </strong>
          <%= @organization.email %>
          <br/>
          <strong>
            <%= Organization.human_attribute_name 'phone' %>
          </strong>
          <%= @organization.phone %>
          <br/>
          <strong>Web</strong>
          <%= link_to_if @organization.web.present?,
                         @organization.web,
                         @organization.web %>
          <br/>
          <strong>
            <%= Organization.human_attribute_name 'public_opening_times' %>
          </strong>
          <br/>
          <%= @organization.public_opening_times %>
          <br/>
          <strong>
            <%= Organization.human_attribute_name 'address' %>
          </strong>
          <%= @organization.address %>
          <br/>
          <strong>
            <%= Organization.human_attribute_name 'neighborhood' %>
          </strong>
          <%= @organization.neighborhood %>
          <br/>
          <strong>
            <%= Organization.human_attribute_name 'city' %>
          </strong>
          <%= @organization.city %>
        </p>
      </div>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">
          <%= t 'global.information' %>
        </h3>
      </div>
      <div class="card-body">
        <p>
          <strong>
            <%= Organization.human_attribute_name 'created_at' %>
          </strong>
          <%= l @organization.created_at, format: :long %>
          <br/>
          <strong>
            <%= Organization.human_attribute_name 'updated_at' %>
          </strong>
          <%= l @organization.updated_at, format: :long %>
          <br/>
          <strong>
            <%= t 'global.member_count' %>
          </strong>
          <%= @organization.members.count %>
          <br/>
          <strong>
            <%= t 'global.balance' %>
          </strong>
          <%= seconds_to_hm(@organization.account.try(:balance)) %>
          <br/>
          <strong>
            <%= t 'global.global_balance' %>
          </strong>
          <%= seconds_to_hm(@organization.try(:global_balance)) %>
        </p>
      </div>
    </div>
  </div>
  <div class="col-sm-5">
    <ul class="nav nav-pills justify-content-end">
      <% if current_user&.manages?(@organization) %>
        <li class="nav-item">
          <%= link_to edit_organization_path(@organization), class: 'nav-link' do %>
            <%= glyph :pencil %>
            <%= t "global.edit" %>
          <% end %>
        </li>
      <% end %>
      <% if current_user&.active?(@organization) %>
        <li class="nav-item">
          <%= link_to new_transfer_path(id: @organization, destination_account_id: @organization.account.id), class: 'nav-link' do %>
            <%= glyph :time %>
            <%= t "global.give_time" %>
          <% end %>
        </li>
      <% end %>
    </ul>
    <%= render "organizations/petition_button", organization: @organization %>
  </div>
</div>

<% if current_user&.active?(@organization) %>
  <%= render "shared/movements" %>
<% else %>
  <div class='alert alert-info'>
    <%= t ".join_timebank" %>
  </div>
<% end %>